stages:
  extract:
    cmd:
      - dvc pull
      - python scripts/extract.py
    deps:
      - scripts/extract.py
    outs:
      - tmp_unzip_path
  transform:
    cmd:
      - python scripts/transform.py
    deps:
      - scripts/transform.py
    outs:
      - ProbaV_UTM_LC100_biome_clusters_V3_global.tif




